### ISSUE TITLE
Persist sorting in library

### ISSUE THREAD

**Issue by fishstik** [connorshea/vglist#1467]
In the user library, similarly to how 'display columns' selections are saved, save which column is sorted when a user clicks it. Automatically load that sorting preference when library is visited.

**Comment by connorshea** [comment]
@fishstik I've implemented this in d52db488a35a2f0eb6c4f18de340fa839511adf1, will deploy the change after CI passes. Thanks for the suggestion, sorry it took me a while! :)

**Comment by fishstik** [comment]
awesome, nice work!
