### ISSUE TITLE
Merge games together

### ISSUE THREAD

**Issue by connorshea** [connorshea/vglist#171]
Like Wikidata's MergeTool, sometimes we may need to merge two games together when someone creates a duplicate entry for a game that already exists. I don't think it'd be worth creating the complex system of merging specific attributes together, so I'd rather just 

- Only moderators or admins could do it. (probably?)
- It would trigger an ActiveJob that would change all the GamePurchases to the new "canonical" item, so no one lost any games from their library.
- It would delete the 'duplicate' item.

Maybe also include a check/warning if the 'duplicate' item has more owners than the 'canonical item', to protect against the case where the user puts the items in backwards.

Also potentially show a preview of each of the games when entering this data.

---------

This needs to:

- Convert 'GamePurchases'
- Convert 'Favorites'
- Update the associated Event records.
- Cleanly handle errors in each of these cases, e.g. if a user owns both games.
- Delete the duplicate entry.

**Comment by AnthonySuper** [comment]
Use `.update_all` for this so it can do it in one SQL `UPDATE` statement.

**Comment by connorshea** [comment]
[2444](https://vglist.co/games/2444) and [21948](https://vglist.co/games/21948) need to be merged together, they were created by Wikidata items that were later merged into one another >.>

**Comment by connorshea** [comment]
- The Beatles: Rock Band: [4662](https://vglist.co/games/4662) and [34759](https://vglist.co/games/34759]
- Pokemon Shield: [33751](https://vglist.co/games/33751) and [29116](https://vglist.co/games/29116)
- The Legend Of Heroes: Trails of Cold Steel: [2444](https://vglist.co/games/2444) and [21948](https://vglist.co/games/21948)
