### ISSUE TITLE
Mantain "Display columns" settings.

### ISSUE THREAD

**Issue by ExiledEye** [connorshea/vglist#1877]
If i choose specific columns hidden and specific showed in my account, if for example a friend from his pc go to my profile he will see HIS settings on my profile.
Basically settings aren't related to profile but saved in the browser (infact if i go incognito mode and go to my profile, columns settings are on default state).
I think it would be better to let the profile owner choose what to be visible or not in HIS profile.

**Comment by connorshea** [comment]
I think this would mostly lead to unexpected behavior for users, e.g. if I hid a column on my user page I wouldn't necessarily expect that to effect everyone who views my library in the future.

**Comment by ExiledEye** [comment]
I understand, but all i wanted to mean is that i think letting the user choose how he wants his library to be showed to others could be a good thing. Also because for example not everyone is using comment, hour played, ecc.. so knowing it he hides a blank space from the library to 'make space' to things he uses but that aren't in the default columns settings like:
I know i don't use comments, but also i know i use platform and store, so i am gonna remove that in favor of the other two. In other hand anyone who has comment enabled in my profile would be useless and a waste of space and aesthetic because of the fact the comments on my profile are blank and he will be penalized because he wouldn't see things i wanted to let him see because they are not enabled in default settings like times replayed or platform.
