### ISSUE TITLE
Thank you for this codebase!

### ISSUE THREAD

**Issue by adityamenon** [connorshea/vglist#2018]
I'm working on a demo for which I need a working rails codebase. I've wasted time on so many of the projects listed [here](https://github.com/eliotsykes/real-world-rails/tree/master/apps), but even some well known ones like `forem` or `discourse` were not working! By that I mean follow the typical instructions to setup and still the site won't work due to some malconfig or the other, issues which I don't have time to fix while working on the demo.

VGList is the only codebase which worked the first time after `./bin/setup`, didn't have dependencies that are a pain to find/install/run, _and_ has functioning seeds that make for a respectable demo.

Thanks again!

**Comment by connorshea** [comment]
Thanks for the comment, I'm happy the project could be helpful! :)
