### ISSUE TITLE
Upgrade to libvips

### ISSUE THREAD

**Issue by connorshea** [connorshea/vglist#731]
Rails 6 deprecates support for ImageMagick (good riddens) in favor of libvips, so we should upgrade.

It'll require changing the Gemfile to no longer use minimagick, changing the Dockerfile to use libvips, and then changing the production server to use libvips.

It'll also require a few changes to our existing code: https://bloggie.io/@kinopyo/upgrade-guide-active-storage-in-rails-6

**Comment by AnthonySuper** [comment]
*riddance

**Comment by connorshea** [comment]
It actually turns out that it still supports ImageMagick, and I'm lazy so I'm not switching for now :D
